name: Update GitHub Profile

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest repositories
        run: |
          curl -s https://api.github.com/users/your-username/repos?sort=updated > repos.json
          cat repos.json | jq -r '.[] | "- [\(.name)](\(.html_url))"' > projects.md

      - name: Update README
        run: |
          sed -i '/<!-- PROJECTS START -->/,/<!-- PROJECTS END -->/c\<!-- PROJECTS START -->\n'$(cat projects.md)'\n<!-- PROJECTS END -->' README.md

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated project list" || echo "No changes to commit"
          git push
